<!DOCTYPE html>
     <!--
  Name: Allison Snyder
  Date: June 15, 2026
  Course: Introduction to Web Design and Development
  Description: Home Page for Allison Snyder Portfolio.
  -->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home | Allison Snyder Portfolio</title>
     <!-- Link to external CSS for styling -->
      <link rel="stylesheet" href="nav.css">
    <link rel="stylesheet" href="style.css?v=2">
    <link rel="shortcut icon" href="FooterIcons/favicon.ico" type="image/x-icon" >
</head>
<body>
   <?php include 'header.php'; ?>
<main>
    <!--Hero Section -->
<section class="hero">
    <div class="hero-text">

         <!-- Welcome section -->

         <h1>Learning Should Feel Like an Adventure</h1>

        <p class="introduction">
        Welcome! I'm Allison Snyder, an educator and graduate student passionate about creating engaging, accessible, and immersive learning experiences. Through technology and creative design, I strive to help students learn through exploration, discovery, and meaningful interaction.
        </p>
         <!-- AI assistance statement -->

        <p class="ai-statement">
        This paragraph was created with assistance from ChatGPT.
        </p>
        <a href="portfolio.php" class="hero-button">
        View My Portfolio →
    </a>
    </div>
        <p class="image-credit">
        Background image generated by ChatGPT.
    </p>
</section>
<!--Focus Section-->
<section class="focus">
    <h2>Areas of Focus</h2>

    <div class="focus-container">

        <article class="focus-card">
            <img src="BrowserIcon.png"
                 alt="Browser window icon representing learning design">

            <h3>Learning Design</h3>

            <p>Building meaningful, immersive learning experiences.</p>
        </article>

        <article class="focus-card">
            <img src="GamingIcon.png"
                 alt="Game controller icon representing game based learning">

            <h3>Game Based Learning</h3>

            <p>Using gaming mechanics to create engaging content.</p>
        </article>

        <article class="focus-card">
            <img src="AccessIcon.png"
                 alt="Accessibility icon representing designing for all learners">

            <h3>Accessibility</h3>

            <p>Designing for all learners in mind.</p>
        </article>
    </div>

    <div class="focus-button-container">
       <a href="about.php" class="focus-button">
        Learn More About Me →
    </a>
    </div>

</section>
</main>
<?php include 'footer.php'; ?>
</body>
</html>